### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by steemypete** [Netherdrake/conductor#10]
I am running conductor 0.3.1 and I get the following message:

```
Monitoring the witness, current misses: 1
Traceback (most recent call last):
  File "/home/witness/anaconda3/lib/python3.6/site-packages/conductor/watchdog.py", line 83, in watchdog
    diff = total_missed() - misses
  File "/home/witness/anaconda3/lib/python3.6/site-packages/conductor/watchdog.py", line 20, in total_missed
    return get_witness(witness('name'))['total_missed']
TypeError: 'NoneType' object is not subscriptable
```

It starts fine, and runs for a little while (5 to 30 minutes, maybe more), but then throws the error.  I am not sure if it is still running, I just have a blinking cursor.

**Comment by Netherdrake** [comment]
This error is generally harmless (ignored).

I don't like the way its currently handled, so I will leave the issue open for now.

**Comment by Netherdrake** [comment]
To be handled in https://github.com/Netherdrake/conductor/issues/14
