### ISSUE TITLE
Using `conductor enable` results in old data being used

### ISSUE THREAD

**Issue by startailcoon** [Netherdrake/conductor#7]
When running `conductor enable` the program will not look up the current values but rather use the cached values.

I've previously set the parameters from another machine and when switching signing node `conductor enable <key>` doesn't use the latest values.

**Comment by startailcoon** [comment]
Part of the code that needs updating
https://github.com/Netherdrake/conductor/blob/e3413d49846ad32eeb77cd18b3788a8909cf3f86/conductor/config.py#L23-L26

**Comment by Netherdrake** [comment]
A better solution would be cache invalidation on start. steemd calls are very time expensive, and should be reduced to a minimum.

**Comment by Netherdrake** [comment]
Fixed in https://github.com/Netherdrake/conductor/commit/1f8b4e605d74a4b4eeb16600309b12bf7d2ad0b6
